apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiii-app
  template:
    metadata:
      labels:
        app: kiii-app
    spec:
      containers:
      - name: kiii-app
        image: spetrovskaaa/kiii-app:latest
        ports:
        - containerPort: 8080

