apiVersion: v1
kind: Service
metadata:
  name: kiii-app-service
spec:
  type: NodePort
  selector:
    app: kiii-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
